-- MySQL Script generated by MySQL Workbench
-- Fri Jul  1 09:48:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Barbearia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Barbearia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Barbearia` DEFAULT CHARACTER SET utf8 ;
USE `Barbearia` ;

-- -----------------------------------------------------
-- Table `Barbearia`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Barbearia`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` DECIMAL NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Barbearia`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Barbearia`.`Funcionario` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFuncionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Barbearia`.`Servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Barbearia`.`Servicos` (
  `idServicos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`idServicos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Barbearia`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Barbearia`.`Venda` (
  `idVenda` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `valorTotal` FLOAT NOT NULL,
  `fkCliente` INT NOT NULL,
  `fkFuncionario` INT NOT NULL,
  PRIMARY KEY (`idVenda`),
  INDEX `fkCliente_idx` (`fkCliente` ASC) VISIBLE,
  INDEX `fkFuncionario_idx` (`fkFuncionario` ASC) VISIBLE,
  CONSTRAINT `fkCliente`
    FOREIGN KEY (`fkCliente`)
    REFERENCES `Barbearia`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkFuncionario`
    FOREIGN KEY (`fkFuncionario`)
    REFERENCES `Barbearia`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Barbearia`.`ServicosFeitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Barbearia`.`ServicosFeitos` (
  `idServicosFeitos` INT NOT NULL AUTO_INCREMENT,
  `fkServicos` INT NOT NULL,
  `fkVenda` INT NOT NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`idServicosFeitos`),
  INDEX `fkServicos_idx` (`fkServicos` ASC) VISIBLE,
  INDEX `fkVenda_idx` (`fkVenda` ASC) VISIBLE,
  CONSTRAINT `fkServicos`
    FOREIGN KEY (`fkServicos`)
    REFERENCES `Barbearia`.`Servicos` (`idServicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkVenda`
    FOREIGN KEY (`fkVenda`)
    REFERENCES `Barbearia`.`Venda` (`idVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Barbearia`.`Agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Barbearia`.`Agenda` (
  `idAgenda` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `fkCliente` INT NOT NULL,
  `fkFuncionario` INT NOT NULL,
  `fkServico` INT NOT NULL,
  PRIMARY KEY (`idAgenda`),
  INDEX `fkCliente_idx` (`fkCliente` ASC) VISIBLE,
  INDEX `fkFuncionario_idx` (`fkFuncionario` ASC) VISIBLE,
  INDEX `fkServico_idx` (`fkServico` ASC) VISIBLE,
  CONSTRAINT `fkCliente`
    FOREIGN KEY (`fkCliente`)
    REFERENCES `Barbearia`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkFuncionario`
    FOREIGN KEY (`fkFuncionario`)
    REFERENCES `Barbearia`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkServico`
    FOREIGN KEY (`fkServico`)
    REFERENCES `Barbearia`.`Servicos` (`idServicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
